import type { Metadata } from 'next'
import './globals.css'
import ThemeContextProvider from './ThemeContext'

export const metadata: Metadata = {
  title: 'Country Glossary',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='h-full' lang="en">
      <body className='h-full'>
        <ThemeContextProvider>
          {children}
        </ThemeContextProvider></body>
    </html>
  )
}
